import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
});

const industry = localFont({
  src: "../public/fonts/IndustryTest-Bold.otf",
  variable: "--font-industry",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` ${interTight.variable} ${industry.variable} h-full antialiased `}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
